version: "3"
services:
  restredis-app:
    build:
      context: .
      args:
        NODE_ENV: production
    ports:
      - "80:5000"
    environment:
      - NODE_ENV=production
      - REDIS_URL=redis
      - REDIS_PORT=6379
    command: npm run start
